Class DataMining.PMML.ExternalIrisData Extends %Persistent
{

Property SepalLength As %Float;

Property SepalWidth As %Float;

Property PetalLength As %Float;

Property PetalWidth As %Float;

Property Species As %String;

Storage Default
{
<Data name="ExternalIrisDataDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>SepalLength</Value>
</Value>
<Value name="3">
<Value>SepalWidth</Value>
</Value>
<Value name="4">
<Value>PetalLength</Value>
</Value>
<Value name="5">
<Value>PetalWidth</Value>
</Value>
<Value name="6">
<Value>Species</Value>
</Value>
</Data>
<DataLocation>^DataMiningDCAD.ExternalIri1197D</DataLocation>
<DefaultData>ExternalIrisDataDefaultData</DefaultData>
<IdLocation>^DataMiningDCAD.ExternalIri1197D</IdLocation>
<IndexLocation>^DataMiningDCAD.ExternalIri1197I</IndexLocation>
<StreamLocation>^DataMiningDCAD.ExternalIri1197S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}