Class DataMining.PMML.RuntimeIrisArray Extends %Persistent
{
	Property Model As %String;
	
	Property PureExecutionTime As %Double;
	
	Property CreationTime As %Double;
	
	Property StoringTime As %Double;
Storage Default
{
<Data name="RuntimeIrisArrayDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Model</Value>
</Value>
<Value name="3">
<Value>PureExecutionTime</Value>
</Value>
<Value name="4">
<Value>CreationTime</Value>
</Value>
<Value name="5">
<Value>StoringTime</Value>
</Value>
</Data>
<DataLocation>^DataMiningDCAD.RuntimeIris8ADCD</DataLocation>
<DefaultData>RuntimeIrisArrayDefaultData</DefaultData>
<IdLocation>^DataMiningDCAD.RuntimeIris8ADCD</IdLocation>
<IndexLocation>^DataMiningDCAD.RuntimeIris8ADCI</IndexLocation>
<StreamLocation>^DataMiningDCAD.RuntimeIris8ADCS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}