Class DataMining.PMML.RuntimeAirbnbArray Extends %Persistent
{
	Property Model As %String;
	
	Property PureExecutionTime As %Double;
	
	Property CreationTime As %Double;
	
	Property StoringTime As %Double;
Storage Default
{
<Data name="RuntimeAirbnbArrayDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Model</Value>
</Value>
<Value name="3">
<Value>PureExecutionTime</Value>
</Value>
<Value name="4">
<Value>CreationTime</Value>
</Value>
<Value name="5">
<Value>StoringTime</Value>
</Value>
</Data>
<DataLocation>^DataMiningDCAD.RuntimeAirb25B8D</DataLocation>
<DefaultData>RuntimeAirbnbArrayDefaultData</DefaultData>
<IdLocation>^DataMiningDCAD.RuntimeAirb25B8D</IdLocation>
<IndexLocation>^DataMiningDCAD.RuntimeAirb25B8I</IndexLocation>
<StreamLocation>^DataMiningDCAD.RuntimeAirb25B8S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}